<?php

declare(strict_types=1);

use AppBundle\Association\MemberType;
use AppBundle\Event\Model\Ticket;
use Phinx\Seed\AbstractSeed;

class Inscriptions extends AbstractSeed
{
    public function run(): void
    {
        // Inscriptions
        $data = [
            [
                'date' => time(),
                'reference' => 'REF-TEST-001',
                'type_inscription' => Ticket::TYPE_2_DAYS,
                'montant' => $GLOBALS['AFUP_Tarifs_Forum'][Ticket::TYPE_2_DAYS],
                'civilite' => 'Mme',
                'nom' => 'Michu',
                'prenom' => 'Bernadette',
                'email' => 'bernadette@yahoo.fr',
                'telephone' => '0601020304',
                'citer_societe' => '1',
                'newsletter_afup' => '1',
                'newsletter_nexen' => '0',
                'id_forum' => Event::ID_FORUM,
                'member_type' => MemberType::MemberPhysical->value,
                'etat' => Ticket::STATUS_PAID,
            ],
            [
                'date' => (new \DateTime("2023-06-25"))->getTimestamp(),
                'reference' => 'REF-TEST-002',
                'type_inscription' => Ticket::TYPE_2_DAYS,
                'montant' => $GLOBALS['AFUP_Tarifs_Forum'][Ticket::TYPE_2_DAYS],
                'civilite' => 'Mme',
                'nom' => 'Jean',
                'prenom' => 'Maurice',
                'email' => 'jean@yahoo.fr',
                'telephone' => '0102030405',
                'citer_societe' => '1',
                'newsletter_afup' => '1',
                'newsletter_nexen' => '0',
                'id_forum' => Event::ID_FORUM,
                'member_type' => MemberType::MemberPhysical->value,
                'etat' => Ticket::STATUS_PAID,
            ],
            [
                'date' => (new \DateTime("2024-01-02"))->getTimestamp(),
                'reference' => 'REF-TEST-003',
                'type_inscription' => Ticket::TYPE_2_DAYS,
                'montant' => $GLOBALS['AFUP_Tarifs_Forum'][Ticket::TYPE_2_DAYS],
                'civilite' => 'Mme',
                'nom' => 'Kirk',
                'prenom' => 'James Tiberius',
                'email' => 'james@starfleet.fr',
                'telephone' => '0102030406',
                'citer_societe' => '1',
                'newsletter_afup' => '1',
                'newsletter_nexen' => '0',
                'id_forum' => Event::ID_FORUM,
                'member_type' => MemberType::MemberPhysical->value,
                'etat' => Ticket::STATUS_PAID,
            ],
            [
                'date' => (new \DateTime("2024-01-02"))->getTimestamp(),
                'reference' => 'REF-TEST-004',
                'type_inscription' => Ticket::TYPE_2_DAYS_AFUP,
                'montant' => $GLOBALS['AFUP_Tarifs_Forum'][Ticket::TYPE_2_DAYS_AFUP],
                'civilite' => 'Mme',
                'nom' => 'Sans',
                'prenom' => 'Cotisation',
                'email' => 'sans@cotisation.fr',
                'telephone' => '0102030406',
                'citer_societe' => '1',
                'newsletter_afup' => '1',
                'newsletter_nexen' => '0',
                'id_forum' => Event::ID_FORUM,
                'member_type' => MemberType::MemberPhysical->value,
                'etat' => Ticket::STATUS_PAID,
            ],
            [
                'date' => time(),
                'reference' => 'REF-TEST-005',
                'type_inscription' => Ticket::TYPE_2_DAYS_AFUP,
                'montant' => $GLOBALS['AFUP_Tarifs_Forum'][Ticket::TYPE_2_DAYS_AFUP],
                'civilite' => 'M',
                'nom' => 'Personne',
                'prenom' => 'Paul',
                'email' => 'paul.personne@mycorp.fr',
                'telephone' => '0102030406',
                'citer_societe' => '1',
                'newsletter_afup' => '1',
                'newsletter_nexen' => '0',
                'id_forum' => Event::ID_FORUM,
                'id_member' => Users::ID_USER_PERSONNE_PHYSIQUE,
                'member_type' => MemberType::MemberPhysical->value,
                'etat' => Ticket::STATUS_PAID,
            ],
            [
                'date' => time(),
                'reference' => 'REF-TEST-006',
                'type_inscription' => Ticket::TYPE_2_DAYS_AFUP,
                'montant' => $GLOBALS['AFUP_Tarifs_Forum'][Ticket::TYPE_2_DAYS_AFUP],
                'civilite' => 'M',
                'nom' => 'Maurice',
                'prenom' => 'Jean',
                'email' => 'userexpire@yahoo.fr',
                'telephone' => '0102030406',
                'citer_societe' => '1',
                'newsletter_afup' => '1',
                'newsletter_nexen' => '0',
                'id_forum' => Event::ID_FORUM,
                'id_member' => Users::ID_USER_EXPIRIE,
                'member_type' => MemberType::MemberPhysical->value,
                'etat' => Ticket::STATUS_PAID,
            ],
            [
                'date' => time(),
                'reference' => 'REF-TEST-007',
                'type_inscription' => Ticket::TYPE_2_DAYS,
                'montant' => $GLOBALS['AFUP_Tarifs_Forum'][Ticket::TYPE_2_DAYS],
                'civilite' => 'Mme',
                'nom' => 'Annulé',
                'prenom' => 'Lepaiement',
                'email' => 'annule@example.com',
                'telephone' => '0601020304',
                'citer_societe' => '1',
                'newsletter_afup' => '1',
                'newsletter_nexen' => '0',
                'id_forum' => Event::ID_FORUM,
                'member_type' => MemberType::MemberPhysical->value,
                'etat' => Ticket::STATUS_CANCELLED,
            ],
            [
                'date' => time(),
                'reference' => 'REF-TEST-008',
                'type_inscription' => Ticket::TYPE_ORGANIZATION,
                'montant' => $GLOBALS['AFUP_Tarifs_Forum'][Ticket::TYPE_ORGANIZATION],
                'civilite' => 'Mme',
                'nom' => 'Super',
                'prenom' => 'Bénévole',
                'email' => 'benevole@example.com',
                'telephone' => '0601020305',
                'citer_societe' => '0',
                'newsletter_afup' => '1',
                'newsletter_nexen' => '0',
                'id_forum' => Event::ID_FORUM,
                'member_type' => MemberType::MemberPhysical->value,
                'etat' => Ticket::STATUS_GUEST,
            ],
        ];

        $table = $this->table('afup_inscription_forum');
        $table->truncate();

        $table
            ->insert($data)
            ->save()
        ;

        // Facturation
        $data = [
            [
                'reference' => 'REF-TEST-001',
                'montant' => $GLOBALS['AFUP_Tarifs_Forum'][Ticket::TYPE_2_DAYS],
                'date_reglement' => time(),
                'type_reglement' => Ticket::PAYMENT_CREDIT_CARD,
                'email' => 'bernadette@yahoo.fr',
                'nom' => 'Michu',
                'prenom' => 'Bernadette',
                'societe' => 'Helios Aerospace',
                'adresse' => '3 rue du chemin',
                'code_postal' => '99002',
                'ville' => 'Ville',
                'id_pays' => 'FR',
                'autorisation' => 'otzbfksgve',
                'transaction' => 'taedsken',
                'etat' => Ticket::STATUS_PAID,
                'facturation' => Ticket::INVOICE_TODO,
                'id_forum' => Event::ID_FORUM,
                'date_facture' => time(),
            ],
            [
                'reference' => 'REF-TEST-002',
                'montant' => $GLOBALS['AFUP_Tarifs_Forum'][Ticket::TYPE_2_DAYS],
                'date_reglement' => (new \DateTime("2023-06-25"))->getTimestamp(),
                'type_reglement' => Ticket::PAYMENT_CHEQUE,
                'email' => 'jean@yahoo.fr',
                'nom' => 'Jean',
                'prenom' => 'Maurice',
                'adresse' => '4 allée des platanes',
                'code_postal' => '29000',
                'ville' => 'Quimper',
                'id_pays' => 'FR',
                'autorisation' => 'otzbfksgvz',
                'transaction' => 'taedskem',
                'etat' => Ticket::STATUS_PAID,
                'facturation' => Ticket::INVOICE_SENT,
                'id_forum' => Event::ID_FORUM,
                'date_facture' => (new \DateTime("2023-06-25"))->getTimestamp(),
            ],
            [
                'reference' => 'REF-TEST-003',
                'montant' => $GLOBALS['AFUP_Tarifs_Forum'][Ticket::TYPE_2_DAYS],
                'date_reglement' => (new \DateTime("2024-01-02"))->getTimestamp(),
                'type_reglement' => Ticket::PAYMENT_BANKWIRE,
                'email' => 'james@starfleet.fr',
                'nom' => 'Kirk',
                'prenom' => 'James Tiberius',
                'adresse' => "3 avenue de l'enterprise",
                'code_postal' => '69003',
                'ville' => 'Lyon',
                'id_pays' => 'FR',
                'autorisation' => 'ozzbfksgvz',
                'transaction' => 'yaedskem',
                'etat' => Ticket::STATUS_PAID,
                'facturation' => Ticket::INVOICE_SENT,
                'id_forum' => Event::ID_FORUM,
                'date_facture' => (new \DateTime("2024-01-02"))->getTimestamp(),
            ],
            [
                'reference' => 'REF-TEST-004',
                'montant' => $GLOBALS['AFUP_Tarifs_Forum'][Ticket::TYPE_2_DAYS_AFUP],
                'date_reglement' => (new \DateTime("2024-01-02"))->getTimestamp(),
                'type_reglement' => Ticket::PAYMENT_CREDIT_CARD,
                'email' => 'sans@cotisation.fr',
                'nom' => 'Sans',
                'prenom' => 'Cotisation',
                'adresse' => "3 avenue de l'enterprise",
                'code_postal' => '69003',
                'ville' => 'Lyon',
                'id_pays' => 'FR',
                'autorisation' => 'ozzbfksgvz',
                'transaction' => 'yaedskem',
                'etat' => Ticket::STATUS_PAID,
                'facturation' => Ticket::INVOICE_SENT,
                'id_forum' => Event::ID_FORUM,
                'date_facture' => (new \DateTime("2024-01-02"))->getTimestamp(),
            ],
            [
                'reference' => 'REF-TEST-005',
                'montant' => $GLOBALS['AFUP_Tarifs_Forum'][Ticket::TYPE_2_DAYS_AFUP],
                'date_reglement' => (new \DateTime("2024-01-02"))->getTimestamp(),
                'type_reglement' => Ticket::PAYMENT_CREDIT_CARD,
                'nom' => 'Personne',
                'prenom' => 'Paul',
                'email' => 'paul.personne@mycorp.fr',
                'adresse' => "3 avenue de l'enterprise",
                'code_postal' => '69003',
                'ville' => 'Lyon',
                'id_pays' => 'FR',
                'autorisation' => 'ozzbfksgvz',
                'transaction' => 'yaedskem',
                'etat' => Ticket::STATUS_PAID,
                'facturation' => Ticket::INVOICE_SENT,
                'id_forum' => Event::ID_FORUM,
                'date_facture' => (new \DateTime("2024-01-02"))->getTimestamp(),
            ],
            [
                'reference' => 'REF-TEST-006',
                'montant' => $GLOBALS['AFUP_Tarifs_Forum'][Ticket::TYPE_2_DAYS_AFUP],
                'date_reglement' => (new \DateTime("2024-01-02"))->getTimestamp(),
                'type_reglement' => Ticket::PAYMENT_CREDIT_CARD,
                'nom' => 'Maurice',
                'prenom' => 'Jean',
                'email' => 'userexpire@yahoo.fr',
                'adresse' => "3 avenue de l'enterprise",
                'code_postal' => '69003',
                'ville' => 'Lyon',
                'id_pays' => 'FR',
                'autorisation' => 'ozzbfksgvz',
                'transaction' => 'yaedskem',
                'etat' => Ticket::STATUS_PAID,
                'facturation' => Ticket::INVOICE_SENT,
                'id_forum' => Event::ID_FORUM,
                'date_facture' => (new \DateTime("2024-01-02"))->getTimestamp(),
            ],
            [
                'reference' => 'REF-TEST-007',
                'montant' => $GLOBALS['AFUP_Tarifs_Forum'][Ticket::TYPE_2_DAYS],
                'date_reglement' => time(),
                'type_reglement' => Ticket::PAYMENT_CREDIT_CARD,
                'nom' => 'Annulé',
                'prenom' => 'Lepaiement',
                'email' => 'annule@example.com',
                'adresse' => '3 rue du chemin',
                'code_postal' => '99002',
                'ville' => 'Ville',
                'id_pays' => 'FR',
                'autorisation' => 'otzbfksgve',
                'transaction' => 'taedsken',
                'etat' => Ticket::STATUS_CANCELLED,
                'facturation' => Ticket::INVOICE_TODO,
                'id_forum' => Event::ID_FORUM,
                'date_facture' => time(),
            ],
            [
                'reference' => 'REF-TEST-008',
                'montant' => $GLOBALS['AFUP_Tarifs_Forum'][Ticket::TYPE_ORGANIZATION],
                'date_reglement' => time(),
                'type_reglement' => Ticket::PAYMENT_NONE,
                'societe' => 'AFUP',
                'adresse' => '',
                'etat' => Ticket::STATUS_CANCELLED,
                'facturation' => Ticket::INVOICE_TODO,
                'id_forum' => Event::ID_FORUM,
                'date_facture' => time(),
            ],
        ];

        $table = $this->table('afup_facturation_forum');
        $table->truncate();

        $table
            ->insert($data)
            ->save()
        ;
    }
}
