<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

class Tarif extends AbstractSeed
{
    public const TYPE_2_DAYS = [
        'id' => 2,
        'technical_name' => 'AFUP_FORUM_2_JOURNEES',
        'pretty_name' => '2 Jours',
        'public' => true,
        'members_only' => false,
        'default_price' => 250.0,
        'active' => true,
        'day' => 'one,two',
        'cfp_submitter_only' => false,
    ];
    public const TYPE_2_DAYS_AFUP = [
        'id' => 3,
        'technical_name' => 'AFUP_FORUM_2_JOURNEES_AFUP',
        'pretty_name' => '2 Jours AFUP',
        'public' => true,
        'members_only' => true,
        'default_price' => 150.0,
        'active' => true,
        'day' => 'one,two',
        'cfp_submitter_only' => false,
    ];
    public const TYPE_ORGANIZATION =
        [
            'id' => 9,
            'technical_name' => 'AFUP_FORUM_ORGANISATION',
            'pretty_name' => 'Organisation',
            'public' => false,
            'members_only' => false,
            'default_price' => 0.0,
            'active' => true,
            'day' => 'one,two',
            'cfp_submitter_only' => false,
        ];

    public function run(): void
    {
        $data = [
            [
                'id' => 0,
                'technical_name' => 'AFUP_FORUM_PREMIERE_JOURNEE',
                'pretty_name' => 'Première journée',
                'public' => true,
                'members_only' => false,
                'default_price' => 150.0,
                'active' => true,
                'day' => 'one',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 1,
                'technical_name' => 'AFUP_FORUM_DEUXIEME_JOURNEE',
                'pretty_name' => 'Deuxième journée',
                'public' => true,
                'members_only' => false,
                'default_price' => 150.0,
                'active' => true,
                'day' => 'two',
                'cfp_submitter_only' => false,
            ],
            self::TYPE_2_DAYS,
            self::TYPE_2_DAYS_AFUP,
            [
                'id' => 4,
                'technical_name' => 'AFUP_FORUM_2_JOURNEES_ETUDIANT',
                'pretty_name' => '2 Jours étudiant',
                'public' => false,
                'members_only' => false,
                'default_price' => 150.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 5,
                'technical_name' => 'AFUP_FORUM_2_JOURNEES_PREVENTE',
                'pretty_name' => '2 Jours prévente',
                'public' => false,
                'members_only' => false,
                'default_price' => 150.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 6,
                'technical_name' => 'AFUP_FORUM_2_JOURNEES_AFUP_PREVENTE',
                'pretty_name' => '2 Jours prévente AFUP',
                'public' => false,
                'members_only' => true,
                'default_price' => 150.0,
                'active' => false,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 7,
                'technical_name' => 'AFUP_FORUM_2_JOURNEES_ETUDIANT_PREVENTE',
                'pretty_name' => '2 Jours étudiant prévente',
                'public' => false,
                'members_only' => false,
                'default_price' => 150.0,
                'active' => false,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 8,
                'technical_name' => 'AFUP_FORUM_2_JOURNEES_COUPON',
                'pretty_name' => '2 jours coupon',
                'public' => false,
                'members_only' => false,
                'default_price' => 200.0,
                'active' => false,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            self::TYPE_ORGANIZATION,
            [
                'id' => 10,
                'technical_name' => 'AFUP_FORUM_SPONSOR',
                'pretty_name' => 'Sponsor',
                'public' => false,
                'members_only' => false,
                'default_price' => 0.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 11,
                'technical_name' => 'AFUP_FORUM_PRESSE',
                'pretty_name' => 'Presse',
                'public' => false,
                'members_only' => false,
                'default_price' => 0.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 12,
                'technical_name' => 'AFUP_FORUM_CONFERENCIER',
                'pretty_name' => 'Conférencier',
                'public' => false,
                'members_only' => false,
                'default_price' => 0.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 13,
                'technical_name' => 'AFUP_FORUM_INVITATION',
                'pretty_name' => 'Invitation',
                'public' => false,
                'members_only' => false,
                'default_price' => 0.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 14,
                'technical_name' => 'AFUP_FORUM_PROJET',
                'pretty_name' => 'Projet PHP',
                'public' => false,
                'members_only' => false,
                'default_price' => 0.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 15,
                'technical_name' => 'AFUP_FORUM_2_JOURNEES_SPONSOR',
                'pretty_name' => '2 Jours par sponsor',
                'public' => false,
                'members_only' => false,
                'default_price' => 200.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 16,
                'technical_name' => 'AFUP_FORUM_PROF',
                'pretty_name' => 'Enseignement supérieur',
                'public' => false,
                'members_only' => false,
                'default_price' => 0.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 17,
                'technical_name' => 'AFUP_FORUM_PREMIERE_JOURNEE_ETUDIANT_PREVENTE',
                'pretty_name' => '',
                'public' => false,
                'members_only' => false,
                'default_price' => 100.0,
                'active' => false,
                'day' => 'one',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 18,
                'technical_name' => 'AFUP_FORUM_DEUXIEME_JOURNEE_ETUDIANT_PREVENTE',
                'pretty_name' => '',
                'public' => false,
                'members_only' => false,
                'default_price' => 100.0,
                'active' => false,
                'day' => 'two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 19,
                'technical_name' => 'AFUP_FORUM_2_JOURNEES_PREVENTE_ADHESION',
                'pretty_name' => '',
                'public' => false,
                'members_only' => false,
                'default_price' => 150.0,
                'active' => false,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 20,
                'technical_name' => 'AFUP_FORUM_PREMIERE_JOURNEE_AFUP',
                'pretty_name' => 'Jour 1 AFUP',
                'public' => false,
                'members_only' => true,
                'default_price' => 100.0,
                'active' => false,
                'day' => 'one',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 21,
                'technical_name' => 'AFUP_FORUM_DEUXIEME_JOURNEE_AFUP',
                'pretty_name' => 'Jour 2 AFUP',
                'public' => false,
                'members_only' => true,
                'default_price' => 100.0,
                'active' => false,
                'day' => 'two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 22,
                'technical_name' => 'AFUP_FORUM_PREMIERE_JOURNEE_ETUDIANT',
                'pretty_name' => 'Jour 1 Etudiant',
                'public' => false,
                'members_only' => false,
                'default_price' => 100.0,
                'active' => false,
                'day' => 'one',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 23,
                'technical_name' => 'AFUP_FORUM_DEUXIEME_JOURNEE_ETUDIANT',
                'pretty_name' => 'Jour 2 Etudiant',
                'public' => false,
                'members_only' => false,
                'default_price' => 100.0,
                'active' => false,
                'day' => 'two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 100,
                'technical_name' => 'EARLY_BIRD',
                'pretty_name' => 'Les yeux fermés - 2 jours',
                'public' => true,
                'members_only' => false,
                'default_price' => 250.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 101,
                'technical_name' => 'EARLY_BIRD_AFUP',
                'pretty_name' => 'Les yeux fermés - 2 jours - AFUP',
                'public' => true,
                'members_only' => true,
                'default_price' => 150.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 102,
                'technical_name' => 'LATE_BIRD',
                'pretty_name' => 'Tarif de soutien - 2 jours',
                'public' => true,
                'members_only' => false,
                'default_price' => 325.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 103,
                'technical_name' => 'LATE_BIRD_AFUP',
                'pretty_name' => 'Tarif de soutien - 2 jours - AFUP',
                'public' => true,
                'members_only' => true,
                'default_price' => 225.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 105,
                'technical_name' => 'LATE_BIRD_PREMIERE_JOURNEE',
                'pretty_name' => 'Late bird - Première journée',
                'public' => true,
                'members_only' => false,
                'default_price' => 225.0,
                'active' => true,
                'day' => 'one',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 106,
                'technical_name' => 'LATE_BIRD_DEUXIEME_JOURNEE',
                'pretty_name' => 'Late bird - Deuxième journée',
                'public' => true,
                'members_only' => false,
                'default_price' => 225.0,
                'active' => true,
                'day' => 'two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 107,
                'technical_name' => 'CFP_SUBMITTER',
                'pretty_name' => 'Personne ayant proposé une conférence - 2 jours',
                'public' => true,
                'members_only' => false,
                'default_price' => 150.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => true,
            ],
            [
                'id' => 108,
                'technical_name' => 'SPECIAL_PRICE',
                'pretty_name' => 'Tarif spécial',
                'public' => false,
                'members_only' => false,
                'default_price' => 0.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 109,
                'technical_name' => 'AFUP_DAY_EARLY',
                'pretty_name' => 'Les Yeux Fermés',
                'public' => true,
                'members_only' => false,
                'default_price' => 50.0,
                'active' => true,
                'day' => 'one',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 110,
                'technical_name' => 'AFUP_DAY_CROISIERE',
                'pretty_name' => 'Tarif de croisière',
                'public' => true,
                'members_only' => false,
                'default_price' => 70.0,
                'active' => true,
                'day' => 'one',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 111,
                'technical_name' => 'AFUP_DAY_LATE',
                'pretty_name' => 'Tarif de soutien',
                'public' => true,
                'members_only' => false,
                'default_price' => 90.0,
                'active' => true,
                'day' => 'one',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 112,
                'technical_name' => 'AFUP_DAY_CFP_SUBMITTER',
                'pretty_name' => 'Personne ayant proposé une conférence',
                'public' => true,
                'members_only' => false,
                'default_price' => 50.0,
                'active' => true,
                'day' => 'one',
                'cfp_submitter_only' => true,
            ],
            [
                'id' => 113,
                'technical_name' => 'AFUP_DAY_LIVE_FREE',
                'pretty_name' => "J'aime l'AFUP, un peu !",
                'public' => true,
                'members_only' => false,
                'default_price' => 0.0,
                'active' => true,
                'day' => 'one',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 114,
                'technical_name' => 'AFUP_DAY_LIVE_SOUTIEN_1',
                'pretty_name' => "J'aime l'AFUP, beaucoup !",
                'public' => true,
                'members_only' => false,
                'default_price' => 5.0,
                'active' => true,
                'day' => 'one',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 115,
                'technical_name' => 'AFUP_DAY_LIVE_SOUTIEN_2',
                'pretty_name' => "J'aime l'AFUP, passionnément !",
                'public' => true,
                'members_only' => false,
                'default_price' => 10.0,
                'active' => true,
                'day' => 'one',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 116,
                'technical_name' => 'AFUP_DAY_LIVE_SOUTIEN_3',
                'pretty_name' => "J'aime l'AFUP, à la folie !",
                'public' => true,
                'members_only' => false,
                'default_price' => 20.0,
                'active' => true,
                'day' => 'one',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 117,
                'technical_name' => 'AFUP_DAY_LIVE_SOUTIEN_4',
                'pretty_name' => "Fan hardcore de l'AFUP",
                'public' => true,
                'members_only' => false,
                'default_price' => 50.0,
                'active' => true,
                'day' => 'one',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 118,
                'technical_name' => 'FORUM_PHP_LIVE_FREE',
                'pretty_name' => "J'aime l'AFUP, j'en suis membre !",
                'public' => true,
                'members_only' => true,
                'default_price' => 0.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 119,
                'technical_name' => 'FORUM_PHP_LIVE_SOUTIEN_1',
                'pretty_name' => "J'aime l'AFUP, un peu !",
                'public' => true,
                'members_only' => false,
                'default_price' => 10.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 120,
                'technical_name' => 'FORUM_PHP_LIVE_SOUTIEN_2',
                'pretty_name' => "J'aime l'AFUP, beaucoup !",
                'public' => true,
                'members_only' => false,
                'default_price' => 30.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 121,
                'technical_name' => 'FORUM_PHP_LIVE_SOUTIEN_3',
                'pretty_name' => "J'aime l'AFUP, passionnément !",
                'public' => true,
                'members_only' => false,
                'default_price' => 50.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 122,
                'technical_name' => 'FORUM_PHP_LIVE_SOUTIEN_4',
                'pretty_name' => "J'aime l'AFUP, à la folie !",
                'public' => true,
                'members_only' => false,
                'default_price' => 70.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 123,
                'technical_name' => 'FORUM_PHP_LIVE_SOUTIEN_5',
                'pretty_name' => "Fan hardcore de l'AFUP",
                'public' => true,
                'members_only' => false,
                'default_price' => 100.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 124,
                'technical_name' => 'FORUM_PHP_LIVE_SOUTIEN_6',
                'pretty_name' => 'BFF de l’AFUP',
                'public' => true,
                'members_only' => false,
                'default_price' => 150.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 125,
                'technical_name' => 'AFUP_DAY_2021_LIVE_1',
                'pretty_name' => 'AFUP Day 2021 Lille / Rennes - édition en ligne, le vendredi 28 mai 2021',
                'public' => true,
                'members_only' => false,
                'default_price' => 25.0,
                'active' => true,
                'day' => 'one',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 126,
                'technical_name' => 'AFUP_DAY_2021_LIVE_2',
                'pretty_name' => 'AFUP Day 2021 Toulouse / Tours - édition en ligne, le vendredi 11 juin 2021',
                'public' => true,
                'members_only' => false,
                'default_price' => 25.0,
                'active' => true,
                'day' => 'two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 127,
                'technical_name' => 'AFUP_DAY_2021_LIVE_3',
                'pretty_name' => 'Le ticket combo AFUP Day 2021 Lille / Rennes + AFUP Day 2021 Toulouse / Tours - éditions en ligne, le 28 mai et le 11 juin 2021',
                'public' => true,
                'members_only' => false,
                'default_price' => 40.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
            [
                'id' => 128,
                'technical_name' => 'AFUP_DAY_2021_LIVE_4',
                'pretty_name' => 'Le ticket combo du coeur, AFUP Day 2021 Lille / Rennes + AFUP Day 2021 Toulouse / Tours - éditions en ligne et coup de pouce de soutien à l’AFUP',
                'public' => true,
                'members_only' => false,
                'default_price' => 70.0,
                'active' => true,
                'day' => 'one,two',
                'cfp_submitter_only' => false,
            ],
        ];

        $table = $this->table('afup_forum_tarif');
        $table->truncate();

        $this->query('ALTER TABLE afup_forum_tarif AUTO_INCREMENT = 10000;');
        $table
            ->insert($data)
            ->save();
        $this->query('UPDATE afup_forum_tarif SET id = 0 WHERE id = 10000;');
    }
}
