# Global
alias ll='ls -alh --color'
alias clean-test-deprecated-log='rm -f /var/www/html/var/logs/test.deprecations.log'
alias group-deprecation-log="touch /var/www/html/var/logs/test.deprecations_grouped.log && cat /var/www/html/var/logs/test.deprecations.log | cut -d \"]\" -f 2 | awk '{\$1=\$1};1' | sort | uniq -c | sort -nr > /var/www/html/var/logs/test.deprecations_grouped.log"

# Symfony
alias console='php bin/console'
