services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    AppBundle\LegacyModelFactory: ~

    PlanetePHP\:
        resource: '../../../sources/PlanetePHP/*Action.php'
        tags: [controller.service_arguments]

    PlanetePHP\FeedArticleRepository: ~
    PlanetePHP\FeedRepository: ~

    Doctrine\DBAL\Configuration: ~
    Doctrine\DBAL\Connection:
        factory: [Doctrine\DBAL\DriverManager, 'getConnection']
        arguments:
            - {url: 'mysql://%database_user%:%database_password%@%database_host%:%database_port%/%database_name%?charset=utf8mb4'}
            - '@Doctrine\DBAL\Configuration'

    Afup\Site\Utils\Configuration:
        autowire: true
