<?php
require_once '../../include/prepend.inc.php';

$sessions_fonctionnelles=array(
    array('horaire'            => '9h - 9h10',
          'nom'                => 'Keynote',
          'resume'             => '',
          'talks'              => array(array('code' => '',
                                              'nom'  => '')),
          'conferenciers'      => array(array('code' => 'alimbourg',
                                              'nom'  => 'Arnaud LIMBOURG'),
                                        array('code' => 'ppenet',
                                              'nom'  => 'Perrick PENET'))),
    array('horaire'            => '9h15 - 10h15',
          'nom'                => 'PHP en 2007 : PHP4 est mort, longue vie à PHP5 & 6',
          'resume'             => '',
          'podcast'            => 'http://audiobank.tryphon.org/casts/866pmw9y',
          'talks'              => array(array('code' => 'html',
                                              'nom'  => 'http://talks.php.net/show/afup07')),
          'conferenciers'      => array(array('code' => 'rlerdorf',
                                              'nom'  => 'Rasmus LERDORF'))),

    array('horaire'            => '10h15 - 11h15',
          'nom'                => 'Web 2.0 : Améliorer l\'experience utilisateur de vos applications PHP grâce à Flex',
          'resume'             => "",
          'podcast'            => 'http://audiobank.tryphon.org/casts/majxhzxd',
          'talks'              => array(array('code' => 'pdf',
                                              'nom'  => 'forumphp2007_flex.pdf')),
          'conferenciers'      => array(array('code' => 'mchaize',
                                              'nom'  => 'Michaël CHAIZE'))),

    array('horaire'            => '11h30 - 12h30',
          'nom'                => 'Retour d\'expérience de la Chambre de Commerce de Paris : du Chaos à l\'Agilité avec PHP',
          'resume'             => "",
          'talks'              => array(array('code' => 'pdf',
                                              'nom'  => 'ForumPHP2007-Agile.pdf')), 
          'podcast'            => 'http://audiobank.tryphon.org/casts/jixgaa37',
          'conferenciers'      => array(array('code' => 'rrougeron',
                                              'nom' => 'Raphaël ROUGERON'))),


    array('horaire'            => '13h45 - 14h',
          'nom'                => 'Etat des lieux de PHP en France et annonce presse',
          'resume'             => '',
          'interactif'         => '/templates/forumphp2007/talks/le_marche_php_en_france/le_marche_php_en_france.htm',
          'podcast'            => 'http://audiobank.tryphon.org/casts/2x4dye7s',
          'talks'              => array(array('code' => 'pdf',
                                              'nom'  => 'ecosystemePHP2007.pdf'),
                                        array('code' => 'pdf',
                                              'nom'  => 'presentation_wampserver.pdf'),),
          'conferenciers'      => array(array('code' => 'cpierredegeyer',
                                              'nom'  => 'Cyril PIERRE de GEYER'),
                                        array('code' => 'Guest',
                                              'nom'  => 'Guest'))),

    array('horaire'            => '14h - 15h',
          'nom'                => 'Retour d\'expérience de l\'integration de PHP chez les grands comptes',
          'resume'             => "",
          'podcast'            => 'http://audiobank.tryphon.org/casts/s9l0ojri',
          'talks'              => array(array('code' => '',
                                              'nom'  => '')),
          'conferenciers'      => array(array('code' => 'diachetta',
                                              'nom'  => 'David IACHETTA'),
                                        array('code' => 'vdupont',
                                              'nom'  => 'Vincent DUPONT'))),
    array('horaire'            => '15h - 16h',
          'nom'                => 'Audit de code, retour d\'experience',
          'resume'             => "",
          'podcast'            => 'http://audiobank.tryphon.org/casts/4xe8gg9w',
          'talks'              => array(array('code' => 'pdf',
                                              'nom'  => 'ForumPHP2007_audit.pdf')),
          'conferenciers'      => array(array('code' => 'ncollignon',
                                              'nom'  => 'Nicolas COLLIGNON'),
                                        array('code' => 'lnyffenegger',
                                              'nom'  => 'Louis NYFFENEGGER'))),
    array('horaire'            => '16h15 - 17h15',
          'nom'                => 'Accessibilite : le developpeur PHP aux premières loges',
          'resume'             => "",
          'talks'              => array(array('code' => 'pdf',
                                              'nom'  => 'forumphp2007_accessibilite.pdf')),
          'conferenciers'      => array(array('code' => 'sdeschamps',
                                              'nom'  => 'Stéphane DESCHAMPS'))),
);
$smarty->assign('sessions_fonctionnelles', $sessions_fonctionnelles);

$sessions_techniques=array(
    array('horaire'            => '9h - 9h10',
          'nom'                => 'Keynote',
          'resume'             => '',
          'talks'              => array(array('code' => '',
                                              'nom'  => '')),
          'conferenciers'      => array(array('code' => 'alimbourg',
                                              'nom'  => 'Arnaud LIMBOURG'),
                                        array('code' => 'gponcon',
                                              'nom'  => 'Guillaume PON&Ccedil;ON'))),
    array('horaire'            => '9h15 - 10h15',
          'nom'                => 'Web 2.0 : Optimisation d\'un site Web 2.0 : le cas de wat.tv',
          'resume'             => "",
          'talks'              => array(array('code' => 'pdf',
                                              'nom'  => 'PHPForum-wat.tv.pdf')),
          'conferenciers'      => array(array('code' => 'jfbustarret',
                                              'nom'  => 'Jean-François BUSTARRET'))),
    array('horaire'            => '10h45 - 11h45',
          'nom'                => 'Optimiser les performances avec un cache d\'OpCode - Le cas Facebook avec APC',
          'resume'             => "",
          'talks'              => array(array('code' => 'pdf',
                                              'nom'  => 'apc@facebook.pdf')),
          'conferenciers'      => array(array('code' => 'bshire',
                                              'nom'  => 'Brian SHIRE'))),
    array('horaire'            => '11h45 - 12h45',
          'nom'                => 'Web 2.0 : Rich Desktop Applications : l\'evolution des methodes de programmation côte serveur',
          'resume'             => "",
          'talks'              => array(array('code' => 'pdf',
                                              'nom'  => 'ForumPHP2007-RDAs.pdf')),
          'conferenciers'      => array(array('code' => 'rrougeron',
                                              'nom'  => 'Raphaël ROUGERON'))),
    array('horaire'            => '14h - 15h',
          'nom'                => 'Web 2.0 : Flex et PHP: techniques d\'intégration pour faire communiquer un client riche et un backoffice PHP',
          'resume'             => "",
          'talks'              => array(array('code' => '',
                                              'nom'  => '')),
          'conferenciers'      => array(array('code' => 'timbert',
                                              'nom'  => 'Thibault Imbert'),
                                        array('code' => 'mchaize',
                                              'nom'  => 'Michael CHAIZE'))),
    array('horaire'            => '15h - 16h',
          'nom'                => 'Sécurite MySQL',
          'resume'             => "",
          'talks'              => array(array('code' => 'pdf',
                                              'nom'  => 'securite.afup2007.pdf')),
          'conferenciers'      => array(array('code' => 'dseguy',
                                              'nom'  => 'Damien SEGUY'))),
    array('horaire'            => '16h30 - 17h30',
          'nom'                => 'PHP::$unicode->i18n() : comment PHP 5.3 et PHP 6 vont changer la donne',
          'resume'             => '',
          'talks'              => array(array('code' => 'pdf',
                                              'nom'  => 'php-i18n.pdf')),
          'conferenciers'      => array(array('code' => 'azmievski',
                                              'nom'  => 'Andrei ZMIEVSKI')))
);
$smarty->assign('sessions_techniques', $sessions_techniques);

$sessions_atelier_1=array(
    array('horaire'            => '9h - 10h30',
          'nom'                => 'Remanier son code pour PHP6',
          'resume'             => "",
          'talks'              => array(array('code' => '',
                                              'nom'  => '')),
          'conferenciers'      => array(array('code' => 'ppenet',
                                              'nom'  => 'Perrick PENET'))),
    array('horaire'            => '11h - 12h30',
          'nom'                => 'Utiliser pleinement le navigateur & les nouveaux clients Web',
          'resume'             => "",
          'talks'              => array(array('code' => '',
                                              'nom'  => '')),
          'conferenciers'      => array(array('code' => 'edaspet',
                                              'nom'  => 'Eric DASPET'))),
    array('horaire'            => '14h - 15h30',
          'nom'                => 'PHP\'s Dirty Secrets',
          'resume'             => "",
          'talks'              => array(array('code' => '',
                                              'nom'  => '')),
          'conferenciers'      => array(array('code' => 'drethans',
                                              'nom'  => 'Derick RETHANS'))),
);
$smarty->assign('sessions_atelier_1', $sessions_atelier_1);

$sessions_atelier_2=array(
    array('horaire'            => '9h - 10h30',
          'nom'                => 'Optimisation MySQL',
          'resume'             => "",
          'talks'              => array(array('code' => '',
                                              'nom'  => '')),
          'conferenciers'      => array(array('code' => 'odasini',
                                              'nom'  => 'Olivier DASINI'))),
    array('horaire'            => '11h - 12h30',
          'nom'                => 'Framework : Simplifier le developpement des interfaces bases de donnees avec Symfony',
          'resume'             => "",
          'talks'              => array(array('code' => '',
                                              'nom'  => '')),
          'conferenciers'      => array(array('code' => 'fpotencier',
                                              'nom'  => 'Fabien POTENCIER'))),
    array('horaire'            => '14h - 15h30',
          'nom'                => 'Les technos Microsoft pour les applications PHP',
          'resume'             => "",
          'talks'              => array(array('code' => '',
                                              'nom'  => '')),
          'conferenciers'      => array(array('code' => 'clauer',
                                              'nom'  => 'Christophe LAUER'))),
);
$smarty->assign('sessions_atelier_2', $sessions_atelier_2);

$smarty->display('resumes.html');
?>
