parameters:
    paybox_ips: [127.0.0.1, 192.168.42.1]
    database_host: dbtest
    database_port: 3306
    database_name: web
    database_user: afup
    database_password: afup
    github_authenticator: "AppBundle\\Security\\TestGithubAuthenticator"
    slack_url: "http://fake-slack-url"

    smtp_host: "mailcatcher"
    smtp_tls: 0
    smtp_username: ""
    smtp_password: ""
    smtp_port: 1025

services:
    AppBundle\Listener\DetectClockMockingListener:
        autowire: true
        tags:
            - { name: kernel.event_listener, priority: 1000 }

    http_client.bluesky_embed:
        class: Symfony\Component\HttpClient\MockHttpClient

    Afup\Tests\Support\Wordpress\FakeWordpressClient: ~
    AppBundle\Event\Wordpress\WordpressClient: '@Afup\Tests\Support\Wordpress\FakeWordpressClient'

    AppBundle\Offices\OfficeFinder:
        class: AppBundle\Offices\NullOfficeFinder
        autowire: true
        arguments: ['@geocoder']

    Afup\Tests\Support\PlanetePHP\FeedHttpClientFactory: ~
    planetephp.http_client:
        class: Symfony\Contracts\HttpClient\HttpClientInterface
        factory: '@Afup\Tests\Support\PlanetePHP\FeedHttpClientFactory'

    PlanetePHP\SymfonyFeedClient:
        arguments:
            $httpClient: '@planetephp.http_client'
