legacy:
    resource: "routing/legacy.yml"

event:
    resource: "routing/event.yml"
    prefix:   /event

connection:
    resource: "routing/connection.yml"
    prefix: /connect

admin:
    resource: "routing/admin.yml"
    prefix: /admin

association:
    resource: "routing/site.yml"
    prefix: /association

talks:
    resource: "routing/talks.yml"
    prefix: /talks

meetups:
    resource: "routing/meetups.yml"
    prefix: /meetups

blog:
    resource: "routing/blog.yml"
    prefix: /blog

groups:
    resource: "routing/groups.yml"
    prefix: /admin/groups

cms_page:
    resource: "routing/cms_page.yml"
    prefix: /p

news:
    resource: "routing/news.yml"
    prefix: /news

member:
    resource: "routing/member.yml"
    prefix: /member

techletter:
    resource: "routing/techletter.yml"
    prefix: /techno_watch

badge_image:
    path: /profile/badge/{id}
    defaults: {_controller: AppBundle:Website\Badge:badge }

company_public_profile_logo:
    path: /profile/company/{id}-{slug}/logo
    defaults: {_controller: AppBundle:Website\CompanyPublicProfile:logo }

company_public_profile:
    path: /profile/company/{id}-{slug}
    defaults: {_controller: AppBundle:Website\CompanyPublicProfile:index }

company_public_profile_list:
    path: /profile/company
    defaults: {_controller: AppBundle:Website\CompanyPublicProfileList:index }

feed_rss:
    path: /rss.xml
    defaults: { _controller: AppBundle\Controller\RssFeedController }

presta_sitemap:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"

global:
    resource: "routing/global.yml"
