admin_talk_export:
  path: /export
  defaults: {_controller: AppBundle\Controller\Admin\Talk\ExportAction}


admin_talk_index:
  path: /update_indexation
  defaults: {_controller: AppBundle\Controller\Admin\Talk\UpdateIndexationAction}
