member_index:
  path: /
  defaults: {_controller: AppBundle:Member:index}

member_contact:
  path: /contact
  defaults: {_controller: AppBundle:MemberShip:contactDetails}

member_membership_fee:
  path: /membership-fee
  defaults: {_controller: AppBundle:MemberShip:membershipFee}

member_membership_fee_download:
  path: /membership-fee/download
  defaults: {_controller: AppBundle:MemberShip:membershipFeeDownload}

member_membership_fee_send_mail:
  path: /membership-fee/send-mail
  defaults: {_controller: AppBundle:MemberShip:membershipFeeSendMail}

member_general_meeting:
  path: /general-meeting
  defaults: {_controller: AppBundle:MemberShip:generalMeeting}

member_general_meeting_reports_download:
  path: /general-meeting-report-download/{filename}
  defaults: {_controller: AppBundle:MemberShip:generalMettingDownloadReport}

member_techletter:
  path: /techletter
  defaults: {_controller: AppBundle:MemberShip:techletter}

member_techletter_unsubscribe:
  path: /techletter-unsubscribe
  defaults: {_controller: AppBundle:MemberShip:techletterUnsubscribe}

member_techletter_subscribe:
  path: /techletter-subscribe
  defaults: {_controller: AppBundle:MemberShip:techletterSubscribe}
  methods: ["POST"]

admin_company:
  path: /company
  defaults: {_controller: AppBundle\Controller\Admin\Membership\CompanyAction}

admin_company_members:
  path: /company/members/{id}
  defaults: {_controller: AppBundle\Controller\Admin\Membership\MembersAction, id: ~}

admin_company_public_profile:
  path: /company/public_profile
  defaults: {_controller: AppBundle:Website\Member\CompanyPublicProfile:index }
