framework:
    http_client:
        scoped_clients:
            http_client.github:
                base_uri: 'https://api.github.com'
                headers:
                    Accept: 'application/vnd.github.v3+json'
            http_client.meetup:
                base_uri: 'https://api.meetup.com'
                headers:
                    Content-Type: 'application/json'
            http_client.bluesky:
                base_uri: 'https://bsky.social'
            http_client.bluesky_embed:
                base_uri: 'https://embed.bsky.app'
            http_client.wordpress:
                base_uri: '%env(WORDPRESS_BASE_URI)%'
                auth_basic: '%env(WORDPRESS_AUTH)%'
                headers:
                    Accept: 'application/json'

when@dev:
    framework:
        http_client:
            scoped_clients:
                http_client.wordpress:
                    verify_peer: false
                    verify_host: false
