connection_github_check:
  path: /github/check
  defaults: { _controller: AppBundle\Controller\Github\ConnectCheckAction }

connection_github:
  path: /github
  defaults: { _controller: AppBundle\Controller\Github\ConnectAction }
