news_list:
  path: /
  defaults: { _controller: AppBundle\Controller\Website\NewsController::list }
  options:
    sitemap: true

news_display:
  path: /{code}
  defaults: { _controller: AppBundle\Controller\Website\NewsController::display }

