talks_list:
  path: /
  defaults: { _controller: AppBundle:Website\Talks:list }
  options:
    sitemap:
      section: talks
      changefreq: monthly

talks_show:
  path: /{id}-{slug}
  defaults: { _controller: AppBundle:Website\Talks:show }

talks_joindin:
  path: /{id}-{slug}/joindin
  defaults: { _controller: AppBundle:Website\Talks:joindin }
