talks_list:
  path: /
  defaults: { _controller: AppBundle\Controller\Website\TalksController::list }
  options:
    sitemap:
      section: talks
      changefreq: monthly

talks_show:
  path: /{id}-{slug}
  defaults: { _controller: AppBundle\Controller\Website\TalksController::show }

talks_joindin:
  path: /{id}-{slug}/joindin
  defaults: { _controller: AppBundle\Controller\Website\TalksController::joindin }
