CREATE TABLE IF NOT EXISTS `afup_accreditation_presse` (
  `id` int(5) unsigned NOT NULL AUTO_INCREMENT,
  `date` int(11) unsigned NOT NULL DEFAULT '0',
  `titre_revue` varchar(255) NOT NULL DEFAULT '',
  `civilite` varchar(4) NOT NULL DEFAULT '',
  `nom` varchar(40) NOT NULL DEFAULT '',
  `prenom` varchar(40) NOT NULL DEFAULT '',
  `carte_presse` varchar(50) NOT NULL DEFAULT '',
  `adresse` text NOT NULL,
  `code_postal` varchar(10) NOT NULL DEFAULT '',
  `ville` varchar(50) NOT NULL DEFAULT '',
  `id_pays` char(2) NOT NULL DEFAULT '',
  `telephone` varchar(40) DEFAULT NULL,
  `email` varchar(100) NOT NULL DEFAULT '',
  `commentaires` text,
  `id_forum` smallint(6) NOT NULL DEFAULT '0',
  `valide` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `id_forum` (`id_forum`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Accreditation presse' AUTO_INCREMENT=1 ;
