DROP TABLE IF EXISTS afup_votes_poids; -- N'existe qu'en prod
DROP TABLE IF EXISTS afup_votes; -- N'existe qu'en prod
DROP TABLE IF EXISTS wikini_acls; -- N'existe qu'en prod
DROP TABLE IF EXISTS wikini_links; -- N'existe qu'en prod
DROP TABLE IF EXISTS wikini_pages; -- N'existe qu'en prod
DROP TABLE IF EXISTS wikini_referrers; -- N'existe qu'en prod
DROP TABLE IF EXISTS wikini_users; -- N'existe qu'en prod
DROP TABLE IF EXISTS rdv_afup; -- N'existe qu'en prod
DROP TABLE IF EXISTS spip_articles; -- N'existe qu'en dév
DROP TABLE IF EXISTS spip_rubriques; -- N'existe qu'en dév
