name: CI

on: [ push, pull_request ]

env:
  php_version: '8.2'

jobs:

  unit:
    name: "Unit tests"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}

      - uses: ramsey/composer-install@4.0.0
        with:
          composer-options: "--no-scripts"

      - name: Tests - Unit
        run: ./bin/phpunit --testsuite unit

  lint:
    name: "Linter"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}

      - uses: ramsey/composer-install@4.0.0
        with:
          composer-options: "--no-scripts"

      - name: Tests - CS Fixer
        run: ./bin/php-cs-fixer fix --dry-run -vv

  phpstan:
    name: "PHPStan"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}

      - uses: ramsey/composer-install@4.0.0
        with:
          composer-options: "--no-scripts"

      - name: PHPStan
        run: php ./bin/phpstan

  functional:
    name: "Functional tests"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - name: Create .env from .env.dist
        run: cp .env.dist .env

      - uses: docker/setup-buildx-action@v4

      - name: Build images with GHA cache
        uses: docker/bake-action@v7
        with:
          files: |
            compose.yml
            compose.override.yml-dist
          targets: |
            apachephp
            apachephptest
          load: true
          set: |
            apachephp.cache-from=type=gha,scope=apachephp-full
            apachephp.cache-to=type=gha,scope=apachephp-full,mode=max
            apachephptest.cache-from=type=gha,scope=apachephp-full
            apachephptest.cache-to=type=gha,scope=apachephp-full,mode=max

      - name: Delete symfony cache
        run: rm -rf var/cache/test

      - name: Tests - Functional
        run: make test-functional

      - uses: actions/upload-artifact@v7
        with:
          name: Functional tests - deprecated log - full
          path: var/logs/test.deprecations.log

      - uses: actions/upload-artifact@v7
        with:
          name: Functional tests - deprecated log - report
          path: var/logs/test.deprecations_grouped.log

  integration:
    name: "Integration tests"
    runs-on: ubuntu-22.04
    env:
      APACHEPHPTEST_TARGET: base

    steps:
      - uses: actions/checkout@v6

      - name: Create .env from .env.dist
        run: cp .env.dist .env

      - uses: docker/setup-buildx-action@v4

      - name: Build images with GHA cache
        uses: docker/bake-action@v7
        with:
          files: |
            compose.yml
            compose.override.yml-dist
          targets: |
            apachephptest
            dbtest
          load: true
          set: |
            apachephptest.cache-from=type=gha,scope=apachephp-base
            apachephptest.cache-to=type=gha,scope=apachephp-base,mode=max

      - name: Delete symfony cache
        run: rm -rf var/cache/test

      - name: Tests - Integration
        run: make test-integration-ci

  rector:
    name: "Rector"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}

      - uses: ramsey/composer-install@4.0.0
        with:
          composer-options: "--no-scripts"

      - name: Rector
        run: php ./bin/rector
